version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Crypto++
          command: 'sudo apt-get install -y libcrypto++-dev libcrypto++-doc libcrypto++-utils'
      - checkout
      - run:
          name: Build Client
          command: 'g++ src/client.cpp -std=c++11 -o c -lpthread -lcrypto++ && rm c'
      - run:
          name: Build Server
          command: 'g++ src/server.cpp -std=c++11 -o s -lpthread -lcrypto++ && rm s'
      - run:
          name: Direct Test
          command: 'mkdir bin && g++ tests/dhtest.cpp -o bin/dh_test -lcrypto++'
      - run:
          name: DH Testing
          command: './bin/dh_test'
