version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Crypto++
          command: 'sudo apt-get install -y libcrypto++-dev libcrypto++-doc libcrypto++-utils'
      - checkout
      - run:
          name: Direct Test
          command: 'g++ tests/dhtest.cpp -o dh_test -lcrypto++'
      - run:
          name: DH Testing
          command: './dh_test'
      - run:
          name: Build
          command: 'cmake -H. -Bbuild && cmake --build build'
      - run:
          name: DH Testing build
          command: './bin/dh_test'
