version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Crypto++
          command: 'sudo apt-get install -y libcrypto++-dev libcrypto++-doc libcrypto++-utils'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: My int test
          command: './bin/myint_test'
      - run:
          name: Bank Testing
          command: './bin/bank_test'
      - run:
          name: DH Testing
          command: './bin/dh_test'
